[#h3_pharmacies_overview]
= Overview

Wavelet serves one of the leaders in the Malaysian healthcare industry, with over 20 years of experience, possessing strengths in diagnostic, laboratory, medical technologies, and other specialised healthcare & pharmaceutical products and services for Medical Practitioners, Hospitals and Corporate Clients. Back in 2013, the customer decided to replace their legacy windows-based software to a web-based ERP system to fit their high pace of growth. Their main objective was to increase the efficiency of their business activities; to obtain a real-time & comprehensive view of their subsidiaries, as well as to strengthen the centralized process flow within the group. Upon the analysis of the customer use case and faced challenges, one of the main objectives of the project has been the automation of the data exchange and transfer between ERP system and Patient Record Management system to capture patient's information and the prescribed medicine (quantity, frequency and usage instruction of medicine). In addition, the Implementation of EMP solution for the supply chain management has been essential to cater for cross-company/branch transactions, including sales, inventory, accounting, reporting.

Serving multiple customers in the pharmaceutical industry, the Wavelet reporting system has been tailored to the specific needs of the industry. For instance, the reporting module allows users to view the expiry month of the medicines and automatically sends notification via email to the respective team. 

Similarly, for the beauty industry, a set of implemented solutions aimed at the implementation of the integrated software infrastructure with the data lake as a backbone of the system, to allow for the seamless data exchange and transfer among ERP, CRM, E-commerce and other solutions. The focus has involved the automation of the data processing among multiple departments, branches and franchises on a real-time basis. The data lake platform has allowed for the centralised consolidated customer database, customer membership & loyalty, product and category management, promotion & voucher management, as well as the rewards system across the entire supply chain and parties. 

