[#h3_process-maintenance-applet_process_template]
= Process Template

== 1.1 Details

Users can fill in details for each field. Process Type field dropdown options can be configured in the Process Type menu. 

If the selected Process Type has its item marking checkbox set to true, a field named Item Marking will appear and be editable by the user.

== 1.2 Output Items

The user can click on the “+” button to go to the Add Output Item page. To remove any selected items, the user can click on the delete button found on each row. No changes are saved before the save button is clicked.

Clicking on the INV Item Code field brings users to the Select Item page where they can select a desired item. The Description, Ratio and UOM fields are auto populated according to the selected item.

Items in the Select Item page must first be created in the Doc Item Maintenance or Inv Item Maintenance Applet. Clicking on any row will select the item.

== 1.3 Input Items

The user can click on the “+” button to go to the Add Input Item page. To remove any selected items, the user can click on the delete button found on each row. No changes are saved before the save button is clicked.

== 1.4 Machine Used

The user can click on the “+” button to go to the Add Machine Used page. To remove any selected items, the user can click on the delete button found on each row. No changes are saved before the save button is clicked.

Clicking on the Machine Code field brings users to the Select Machine page where they can select a desired machine. The Machine Code field is auto populated according to the selected item.

Machines in the Select Machine page can be configured in the Machine menu. Clicking on any row will select the machine.

== 1.5 Machine Settings

After a Process Template is created, users can add more information to the process template by editing it. The user can click on a process template row item to edit it.



