[#h4_ecomsync_item_api]
= Ecomsync Item Api

Ecomsync item is where the product stored for marketplace such as Lazada, Shopee, CpCommerce or any Ecommerce platform. In order for any item to be created/synced from marketplace to blg database or vice versa, the item must be created in financial item beforehand through api ((xref:h4_financial_item_api[xrefstyle=full])) or doc item maintenance applet.


* bl_fi_mst_ecomsync_item_hdr
** compulsory table that need to be passed
** consist of details of marketplace product

* bl_fi_mst_ecomsync_item_ext
** consists of extra information of the product that not exist in header or line table

* bl_fi_mst_ecomsync_item_line
** this table is storing marketplace product details for child item


== Create Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/63fba45dbd3fc-create-ecomsync-item-etl-ep

== Update Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/bebff518c890b-update-ecomsync-item-etl-ep

== Get all Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/0ee6f6e50f5e3-get-all-ecomsync-item-etl-ep

== Get Ecomsync Item by Guid
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/be1c6ce90be69-get-ecomsync-item-by-guid-etl-ep

== Get Ecomsync Item by Criteria
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/6df7f69f6c4f8-get-ecomsync-item-by-query-etl-ep

== Delete Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/9545dd93ac5b4-delete-ecomsync-item-by-guid-etl-ep

== Create Ecomsync Item Extension
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/4a50f7cd4d7cf-create-ecomsync-item-extension-etl-ep

== Update Ecomsync Item Extension
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/15ff4a9d542f9-update-ecomsync-item-extension-etl-ep

== Get All Ecomsync Item Extension
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/e51e41d5fc1a9-get-all-ecomsync-item-extensions-etl-ep

== Get Ecomsync Item Extension by Guid
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/97913c9d1d2ea-get-ecomsync-item-extension-by-guid-etl-ep

== Get Ecomsync Item Extension by Criteria
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/b0b7a9b4c805d-get-ecomsync-item-extension-by-query-etl-ep

== Delete Ecomsync Item Extension
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/b82778b66b76c-delete-ecomsync-item-extension-by-guid-etl-ep

== Create Ecomsync Item Line
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/5df4b6cc4f6df-create-ecomsync-item-line-etl-ep

== Update Ecomsync Item Line
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/712933bd78ea8-update-ecomsync-item-line-etl-ep

== Get All Ecomsync Item Line
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/6eddda835861e-get-all-ecomsync-item-lines-etl-ep

== Get Ecomsync Item Line By Guid
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/c6d77508653f7-get-ecomsync-item-line-by-guid-etl-ep

== Get Ecomsync Item Line by Criteria
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/92a7efd385ddd-get-ecomsync-item-line-by-query-etl-ep

== Delete Ecomsync Item Line
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/1c8eb2f0066e1-delete-ecomsync-item-line-by-guid-etl-ep

== Add Multiple Files In Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/d968514aaa538-add-files-for-ecomsync-item-etl-ep

== Get File In Ecomsync Item
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/958568a53ac93-get-file-of-ecomsync-item-etl-ep
