[#h4_sales_order_api]
===== Sales order API

Sales order consists of five tables for data storing which are:

* bl_fi_generic_doc_hdr
** compulsory table that need to be passed
** consist of details of sales order including sales order number, billing and and delivery details

* bl_fi_generic_doc_line
** consists of details ofitem including voucher involve in sales order transaction

* bl_fi_generic_doc_ext
** this table store extra information which not stored in bl_fi_generic_doc_hdr 

* bl_fi_generic_doc_event
** this table for report tracking purpose. For example when sales order successfully synced from marketplace, the row will be inserted to indicate the syncing process happened

* bl_fi_generic_doc_link
** this table to link the generic document. It can link from any server doc type such sales order, sales invoice etc

Calculation in line level:

[%header,format=csv]
|===
include::genDocLinePricingCalc.csv[]
|===

====== Create sales order
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/efd10d9cc76c9-internal-sales-order-insert-etl-ep

====== Update sales order
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/94aaf04d32918-internal-sales-order-update-etl-ep

====== Get all sales order
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/ab3844710a466-internal-sales-order-get-all-etl-ep

====== Get sales order by guid
https://bigledger.stoplight.io/docs/blg-akaun-api-docs-public/0c36501cddfbf-internal-sales-order-get-by-guid-etl-ep

[#h5_frequently asked questions]
====== Frequently Asked Question

*PNS VS STL_MTHD*

PNS(product and services) is txn_type which involve the transaction of product or service while STL_MTHD is the settlement method involved payment in any kind of form such as cash, debit card, or voucher. Once there is order created, that is considered PNS as it involve sales of the product. When the customer pay by cash, the receipt is issued and this is considered as STL_MTHD. To understand further, you may watch the video in the link 
https://drive.google.com/file/d/1rzXKlOXaXKT2ADwugYIrjJvxbQGYuKMY/view


*Can sales order being edited multiple times?*

Sales order can not be edited once the sales order is finalized. In order to know if the sales order is finalized, you may refer to column bl_fi_generic_doc_hdr.posting_status. If the column is 'FINAL', the data can not be edited except for remarks column.

// * What if sync wrongly, need to cancel / void?


// * What if there's membership points to be rewarded? 

// *which server doc number should be used to indicate sales order number when sales order being generated



