[#h3_car_workshops_overview]
= Success Story 3 : Automotive & Workshop Industry

Wavelet is an entrusted solution provider to one of the most well-known European market players in the automotive industry (with currently served headquarters in Singapore and Malaysia). One of the key challenges faced by the client was the lack of customer engagement and personalized ‘touch’ when executing their marketing activities. No software had been set in place to stay connected with customers and provide convenience for their financing needs. The scope of the project has involved a CRM Application which consists of both Mobile Application and Admin Console. The Mobile application is running on Android and iOS which addresses the needs of multiple car brands. The Admin Console back-office system is a complete package that administers marketing events, promotions, member card privileges and custom messages. It also incorporates other versatile features such as invoice management, audit trail reports, target group management, updating of terms and conditions, and landing pages. In addition to optimising the data exchange between the automotive business and end customers via an implemented CRM app, Wavelet has integrated the software to the current back-end ERP system for the automation of the financial module and invoice management. The system allows the car owner to pay their car loan directly via the app, with the data being pushed directly to the back-end system for further processing. 

In addition, Wavelet serves several largest car servicing and workshop market players in Malaysia. One of the long-served clients is a renowned car servicing centre, established in the 1980s, with a wide network across the country. Servicing more than 15,000 vehicles monthly, the customer owns 20 branches in the Klang Valley and beyond. The key challenges that the customer had faced with their previous system were : (i) Slow deployment for new outlets; ii) No support from the software vendor; iii) Manual data submission; iv) No standardization & duplication of item codes. 

With the newly implemented systems, the management obtained increased capacity to control activities and have a comprehensive view of their business with instant access to critical data, anytime, anywhere while also gaining total control over multiple companies and branches in one single console.  In addition, the software has provided effective support to optimise cash flow and inventory, reduce handling costs and improve speed, eliminating duplicate data entries and minimising human error.

