[#h3_cpcom_mod_introduction]
= Introduction

This guide covers the following topics:

* Project Implementation +
    The implementation guide provides you the necessary steps to implementing a brand new cp-commerce project. This include the preparation needed before the implementation, the workflow and knowledge that you will need, what to do first, and what to do next etc.

* Content Management System +
    This chapter provides all the features and functions of the Content Management System for CP-Commerce module to guide you with various configurations and settings

* Order Fulfillment +
    We discuss about the shipping fees, various scenarios in order fulfillment, integration with third party logistics, and applets required for in-house delivery fleet, self pickup etc.

* Customer Experience +
    This chapter covers the topics of how cp-commerce operators could optimize the user journey and experience by discussing about the lifecycle of a shopping cart, how to do cross selling, the use of proactive bots and spending limits to provide a better overall experience.

* ERP Integration +
    The CP-Commerce is not just a shopping cart, its backboned is built with a solid ERP foundation, this chapter provide insights into the possibilities of using CP-Commerce to achieve much more by leveraging on the ERP data out of the box.

* Memberships +
    In order to promote greater loyalty among the customers, CP-Commerce is embedded with Membership program. The mechanism and features of membership points reward and redemption are covered in this chapter.

* o2o +
    Being much more than just a shopping cart, the cp-commerce when used together with the Contact Center module, Sales Order Applet, Point of Sales, Issue Tracker, RMA applets and so on, businesses can implement o2o seamlessly without integrations!

* Payment and Collection
    In this chapter, we talk about the cashbooks and settlement methods, partial settlements, payment integrations, recurring payment and collection.

* Product Maintenance
    Most of the product configurations are done in the "Doc Item Maintenance Applet". We discuss about how the settings in Doc Item Maintenance applet relates to cp-commerce. This would include, add-ons, attributes, categories, extended warranty, made-to-orders, pre-orders, pricing scheme, product bundle and variants, reviews and rating, unit of measure etc.

* Traffic Generation
    Having a shopping cart is not good enough, there is much more that we could do to drive traffic to the website. In this chapter, we talk about affiliate programs, google ads, google analytics, meta ads, referral program, SEO, UTM tracking and vouchers.

* B2B2C
    With various other integrations, for example Apple - ACPP, Microsoft ESD, Product QR Code, OCR, Multi-Vendor functionality, T2T and marketplace connector module, the CP-Commerce has all the necessary ingredients for businesses to use it for B2B2C. This chapter elaborate how businesses could implement B2B2C.


    
