[#h2_project_implementors]
=== Project Implementors

Understanding of the Akaun Platform is a prerequisite for successful implementation of any projects
using the BigLedger platform.

In this section, we are going to list down what the Platform System Administrators need to do, in order for a company to start using the Akaun-Platform.


[#h3_project_impl_subscription_setup]
==== Subscription setup in Akaun Platform

The Platform System Administrator should be using the "Platform SysAdmin Applet" to create a subscription, and then add the OWNER / ADMIN of the tenants (usually the MIS Manager or business owners) as a MEMBER of this subscription. By adding a user to this subscription, he/she will be able to create new Applet Catalogs using the "Tenant Admin Applet".

(_At the time of writing as per 2022-05-19, the new "Platform SysAdmin Applet" and "Tenant Admin Applet" are being redeveloped, hence, we will use the work around method to achieve this for the time being._)

// TODO: [BLGPD-7376] Tenant Admin Applet - Screen Mock Up and Behavior 

[#h3_project_impl_tenant_setup]
==== Tenant setup in Akaun Platform

Only the Akaun Platform system administrators (Wavelet and BigLedger employees) are able power up the tenant for you. The Platform System administrators need to ensure that when creating the Tenant, the correct subscription account is chosen.

Please email mailto:jira-mis@wavelet.net[] to request for the tenant to be created.

(_We do not plan to allow non-System Administrators to create new tenants at the moment, because our Billing engine and FPX recurring payment authorization is not ready yet. Once these are ready, we may consider allowing businesses that have authorized us to bill and charge be able to create tenants in the "Tenant Admin Applet" _)

[#h3_project_impl_applet_catalog_setup]
==== Applet-Catalogs 

Think of applet-catalog as a collection of applets, tagged with RANK and TENANT. When the OWNER/ADMIN of the applet-catalogs can add applets to it, and they have to specify the "rank" and "tenant". This also mean, within the same applet-catalog, it is possible to include the same applet that links to different tenants. 

The ADMIN/OWNER of the applet-catalog also need to add users to the applet-catalogs, and they can add them as OWNER/ADMIN/MEMBER to the applet-catalogs. Only OWNER/ADMIN of the catalogs can manage the applet-catalog (adding / removing applets and users from the applet-catalogs).

All OWNER/ADMIN/MEMBER of an applet-catalog can see the applets in this catalog and install these applets when they use the "Applet Store => Private"

When the users install applets from the "Applet Store" the RANK/TENANT tags will be applied to grant the users the respective permissions when they open the respective applet. Only the OWNER/ADMIN of the applets will be able to see and click on the "Settings" on the left handside menu of the applets to perform some further configuration for the applet. (This is not the same as the rank of the users in the applet-catalog).



[#h3_project_impl_core_module]
==== Configuration of Core Modules

The Core Module consist of the following applets:

* Chart of Account Applet

* Organization Applet

* Tax Configuration Applet

* Cashbook Applet

* Doc Item Maintenance Applet

* Inventory Item Maintenance Applet

* Customer Maintenance Applet

* Supplier Maintenance Applet

* Employee Maintenance Applet

* Entity Maintenance Applet

These applets should be installed, configured in proper sequence, before you proceed to install the other applets.

See <h2_core_module> for more details.


// This is the page break

<<<<<<<<<<<