[#h3_group_maintenance_group_listing]
= 3.0 Group Listing

Please click the "+" button to add a new group.

Please fill up the compulsory * information for creating the group. 

Compulsory Information:

    1. Group Name
    2. Group Code
    3. Group Email
    4.  Please Select the Group Visibility from the list.
    5. Please Select the Group Joining from the list

After filled up all Compulsory * information, Please click "Create Group" to add a new group.

After adding the group, it will be listed in the main page. Please click on the group to edit it. 

Please edit the Group general information from the "Edit general info" tab.

Only the following fields can be edited:

    1. Group Name
    2. Group Visibility
    3. Group Joining
    4. Group Status

Please add or edit members of the group from the "Edit Members" tab.

Please search user email- once the users sign-up in the akaun.com, their email will be listed in 'Select Email'. 

Please select the rank-Please "Select Rank" to differentiate the role of the member. 

Please select the status.

After adding the members in the group, you can Edit or Delete them from the "Members List".

Please add or edit permission from the "Edit Permission" tab.

You can "Select permission" from the list to Add permission.

After adding the permission, you can Edit or Delete it from the "Permission".
